packages:
  code.internetisalie.net/slogan:
    config:
      all: true
      recursive: true
      inpackage: true
      filename: "mocks_test.go"
      dir: "{{.InterfaceDir}}"
      structname: "Mock{{.InterfaceName}}"  # Updated variable
      pkgname: "{{.SrcPackageName}}"        # Fixed error here
